### ISSUE TITLE
rich text content isnt formatted on NextJs

### ISSUE THREAD

**Issue by MAnasKhalid** [thibaudcolas/nextjs-loves-wagtail#7]
```[tasklist]
### Tasks
```

**Comment by thibaudcolas** [comment]
@MAnasKhalid yes, this is a beginner tutorial where there isn’t time to dive into rich text requirements. See https://github.com/wagtail/wagtail/issues/2695 and https://areweheadlessyet.wagtail.org/rich-text for more information.
